### ISSUE TITLE
non ARC project

### ISSUE THREAD

**Issue by cassio-rossi** [ekohe/EKStreamView#3]
Hi. I would like to convert this code to non-ARC because I'm trying to put it on my project that is already non-ARC and it will be very difficult to change all my code to ARC at this point.

Also I'm have an issue: every time I re-call [stream reloadData](specially when rotating the device), the App crashes.

Thanks and congrats for the code.

Cassio

**Comment by cassio-rossi** [comment]
Ok. I did it. Just add the flag -fobjc-arc on the EKStreamView.m on Build Phases on Targets. That did the trick and fix the problem.
Cassio

**Comment by Xenofex** [comment]
@kazziosoftware If you have a lot of files that requires ARC, just create a new target of cocoa static library with ARC, and add all that files to this target. Then make your main target depend on this, and link it to this cocoa library.
